### ISSUE TITLE
블랙잭 규칙

### ISSUE THREAD

**Issue by smallsnail-study** [megabyte-school-practice1/blackjack-game#3]
#설명
- blackjack game 규칙 내용조사

#해야할 일
- [x] blackjack game 위키검색

#참조
https://ko.wikipedia.org/wiki/%EB%B8%94%EB%9E%99%EC%9E%AD

**Comment by HongGuma** [comment]
`- [ ]` : 체크박스 표시? 표현? 이라서 안에 숫자 안넣으셔도 됩니당

**Comment by HongGuma** [comment]
오른쪽에 Assigness랑 Labels를 설정할 수 있어요.
Assigness는 본인 Labels는 documentation으로 설정해주세요!
