### ISSUE TITLE
블랙잭 게임 인원 

### ISSUE THREAD

**Issue by suji5262** [megabyte-school-practice1/blackjack-game#4]
#설명
- 블랙잭 게임 인원 적겠습니다.

#해야할 일
- [x] 블랙백 게임 임원 적기

#참조
[https://namu.wiki/w/%EB%B8%94%EB%9E%99%EC%9E%AD(%EC%B9%B4%EB%93%9C%EA%B2%8C%EC%9E%84]

**Comment by HongGuma** [comment]
오른쪽에 Assigness랑 Labels를 설정할 수 있어요.
Assigness는 본인 Labels는 documentation으로 설정해주세요!
